spring:
  profiles:
    active: dev1

eureka:
  instance: 
    # 每间隔1s，向服务端发送一次心跳，证明自己依然”存活“
    lease-renewal-interval-in-seconds: 5
    # 告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉。
    lease-expiration-duration-in-seconds: 8
    prefer-ip-address: true
    # instanceId:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver.com:8761/eureka/

---

spring:
  profiles: dev1

  application:
    name: client-1
server:
  port: 8081

---

spring:
  profiles: dev2

  application:
    name: client-2
server:
  port: 8082